server:
  port: 8080

spring:
  redis:
    database: 0
    host: mq-redis
    port: 6379
    password: das123

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stolon-proxy-service.qsc-psql.svc.cluster.local:5432/code_system
    username: postgres
    password: daship123
    hikari:
      poolName: authServerCP
      maximum-pool-size: 10